# Generated by Django 5.1.6 on 2025-03-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0002_alter_reward_end_date_alter_reward_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="food",
            new_name="menu",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="complate",
            new_name="complete",
        ),
        migrations.AddField(
            model_name="history",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status_order",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
