# Generated by Django 5.1.6 on 2025-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_order",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
