# Generated by Django 5.1.6 on 2025-03-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0003_rename_food_history_menu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="unit_price",
            field=models.IntegerField(),
        ),
    ]
