# Generated by Django 5.1.6 on 2025-03-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0003_alter_order_status_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_order",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("preparing", "กำลังเตรียมอาหาร"),
                    ("completed", "สำเร็จ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
