# Generated by Django 6.0.7 on 2026-07-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0004_alter_order_status_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="points_used",
            field=models.IntegerField(default=0),
        ),
    ]
