# Generated by Django 6.0.7 on 2026-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0005_order_discount_amount_order_points_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
