# Generated by Django 6.0.7 on 2026-07-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0006_alter_menu_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                default="default_menu.jpg", upload_to="menu_images/"
            ),
        ),
    ]
