# Generated by Django 6.0.7 on 2026-07-20 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0007_alter_menu_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="image_url",
        ),
    ]
