# Generated by Django 6.0.7 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0008_remove_menu_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                default="menu_images/default_menu.jpg", upload_to="menu_images/"
            ),
        ),
    ]
