# Generated by Django 5.1.6 on 2025-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reward",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reward",
            name="start_date",
            field=models.DateField(),
        ),
    ]
